1回目のレビューを頂いて修正
pachikuriii/the-birthday-times pull request #2
Opened 2022-08-12 08:08 UTC by pachikuriii

2022-08-13 12:09 UTC, pachikuriii reviewed
コードを書く中で迷ったポイントについて、いくつかコメントを書かせていただいています🙏

2022-08-13 12:09 UTC, pachikuriii commented on .eslintrc.json
> +}
> npx eslint . を実行しても ESLint が正しく動作しなかったので、設定を確認してみてください。

設定ファイルをgitの管理下におくことでESLintの設定としました。

2022-08-13 12:09 UTC, pachikuriii commented on the-birthday-times.js
> +    this.#checkApiKey()
API キーが設定されていることを確認するのはどのタイミングがいいのか…と悩みました。コマンド実行した際にAPIキーがあるかどうかをチェックした方が親切なのか…？と思いつつ、役割としてはニュースを取得するためのリクエストを送る際に使うものだと思ったので、`getNews`に含めました。

2022-08-15 22:30 UTC, cafedomancer commented on .eslintrc.json
> +}
設定ファイルがないためにエラーが出ていたのでこの方法でよいです 🙆 設定は config file に書くのでも package.json に書くのでもどちらでもよいと思います。package.json に設定を書くようにすると、他のツールの設定も package.json に書きたくなり、そうすると package.json が際限なく膨らんでいってしまうので、個人的には config file を用意するようにしています。

2022-08-15 23:05 UTC, cafedomancer commented on the-birthday-times.js
> +    this.#checkApiKey()
タイミングとしては最初に表示されていたほうが親切かなーと思います。また、以下のクラス図を見てもらいたいのですが、クラスの責務という観点からも `checkApiKey()` が `Birthday` クラスに含まれているのは、ちょっとおかしいかもしれません。オブジェクトの振る舞いを日本語にしてみると、そのことが分かりやすいです (「誕生日が API キーをチェックする」) 。なので、まずは当初の関数ベースの形で処理の流れを改善してもらうほうがよいかなーと思いました。

```mermaid
classDiagram
    class Birthday {
        +number year
        +number month
        +number dateFormat
        +getNews()
        +displayNews()
        -checkApiKey()
        -getNewsIndexNum()
    }
```

2022-08-15 23:33 UTC, cafedomancer commented on the-birthday-times.js
> +     ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣`
dedent を使っているのであれば以下のようにしたらいいんじゃなかなと思いました。

```suggestion
  const title = dedent`
    :￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣:
    :                                                                      :
    :              ${color.bold('🗞   T h e   B i r t h d a y   T i m e s   🗞')}             :
    :                                                                      :
    :                                                                      :
     ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
  `
```

2022-08-18 13:55 UTC, cafedomancer commented on the-birthday-times.js
> +    exec()
`exec()` を導入した理由を教えてください。 `exec()` を導入することによる効果が分からなかったためです。

2022-08-18 13:55 UTC, cafedomancer commented on the-birthday-times.js
>      }
`main()` 内の他の関数呼び出しと抽象度が揃うように、この処理も関数に切り出すといいんじゃないかなーと思います。

2022-08-21 02:45 UTC, pachikuriii reviewed
ご確認いただきありがとうございます！
`exec()`について2点コメントしています。
目を通していただけると幸いです。🙏

2022-08-21 02:45 UTC, pachikuriii commented on the-birthday-times.js
> +    exec()
当初、このように書いていたのですが処理の流れを掴みづらく感じてしまいました。
```js
async function main () {
  try {
    if (!process.env.NYTIMES_KEY) {
      throw new Error(color.red("Please set your API key on your operating system.\nTo set environment variables on macOS or Linux, run the export command from the terminal: export NYTIMES_KEY='YOUR-API-KEY'"))
    }
    showTitle()
    const birthday = await getBirthday()
    const news = await getNews(birthday)
    await loadingMessage()
    displayNews(news)
  } catch (error) {
    console.error(error.message)
  }
}
```

エラーを投げない場合は`exec()`として別の箇所にまとめて記載し、それを呼び出すようにした方が処理の流れが掴みやすく感じたため、正常系の処理のまとまりとして`exec()`を導入しました。

なぜ読みにくく感じたのか？というところではtry...catch構文を使ってコードを書くことが初めてだったこともあり、エラーを投げる場合の処理の流れについて理解しきれていなかったからという点が考えられます。理解しようと集中しすぎるあまり、他の処理を多く構文の中に書きたくなかったのかもしれません。

2022-08-21 02:45 UTC, pachikuriii commented on the-birthday-times.js
> +    exec()
復習したのち、例外発生時は
(1) try...catch構文の`try`ブロック内で例外が発生すると、その時点でそれ以降の処理は実行されずに`catch`節に処理が移行。
(2)`catch`節では、`try`ブロック内で例外が発生すると、`error`識別子でキャッチしたエラーオブジェクトを参照することで`catch`節の処理としてメッセージの表示が実行される
という流れになることを理解しました。

すなわち、例外発生しなければtryブロック内に書いた処理は正常系として上からプログラムが実行されるため、`exec()`として外に切り出すメリットはない…ということで効果について質問いただいたのかなと思いました。いかがでしょうか？

また、`main()`という関数をわざわざ記載してるのに外に書くと関数に`main`とした意味もなくなる…と思ったので`exec()`に書いた処理は`main()`に戻して修正しています。

2022-08-23 00:59 UTC, cafedomancer commented on the-birthday-times.js
> +    exec()
> すなわち、例外発生しなければtryブロック内に書いた処理は正常系として上からプログラムが実行されるため、exec()として外に切り出すメリットはない…ということで効果について質問いただいたのかなと思いました。いかがでしょうか？

動きの理解については OK そうに見えました 🙆 ここでの質問は、当初のフィードバックである「`main()` 関数内から呼び出している関数の抽象度が揃っていない」というものに基づいています。`exec()` 関数を導入すると、抽象度がさらにバラバラになってしまうためです。ので `exec()` の処理を `main()` に戻す、というので対応としては OK だと思います。抽象度については提出物のページに別途コメントします 💁

2022-08-23 01:52 UTC, cafedomancer commented on the-birthday-times.js
> +`
これはもう 1 段インデントを下げてもよさそうです。

2022-08-23 01:53 UTC, cafedomancer commented on the-birthday-times.js
>  main()
`main()` の直前の空行がなくなってしまっていそう...？

2022-08-24 11:03 UTC, pachikuriii reviewed
エラー処理について1点質問させていただいております。
目を通していただけると嬉しいです🌸

2022-08-24 11:03 UTC, pachikuriii commented on the-birthday-times.js
> +    throw new Error(color.red("Please set your API key on your operating system.\nTo set environment variables on macOS or Linux, run the export command from the terminal: export NYTIMES_KEY='YOUR-AP
エラーの出し方について疑問に思った部分があったので質問させていただきます🙏
APIキーが確認できない場合、`throw new Error`でプログラムがそもそも実行できない状態に今回はしてみているのですが、例外の処理の仕方としてこの方法はいい方法なのでしょうか？
アドバイスいただけますとうれしいです🙏

APIキーがない状態でプログラム実行した時は今は下記のように表示されます。

```
❯ node the-birthday-times.js            
/Users/SayaTakahashi/the-birthday-times/the-birthday-times.js:21
    throw new Error(color.red("Please set your API key on your operating system.\nTo set environment variables on macOS or Linux, run the export command from the terminal: export NYTIMES_KEY='YOUR-API-KEY'"))
          ^

Error: Please set your API key on your operating system.
To set environment variables on macOS or Linux, run the export command from the terminal: export NYTIMES_KEY='YOUR-API-KEY'
    at ensureApiKey (/Users/SayaTakahashi/the-birthday-times/the-birthday-times.js:21:11)
    at main (/Users/SayaTakahashi/the-birthday-times/the-birthday-times.js:11:3)
    at Object.<anonymous> (/Users/SayaTakahashi/the-birthday-times/the-birthday-times.js:100:1)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.6.0
```


`throw new Erro`ではなく、前回までのコードを引き継いで try...catchを使った場合は誕生日を入力してようやくプログラムが止まるようになってるためプログラムが異常なのか正常なのか分かりづらい上、ユーザーにも不親切なのでは？と思いました。
```js
function ensureApiKey () {
  try {
    if (!process.env.NYTIMES_KEY) {
      throw new Error(color.red("Please set your API key on your operating system.\nTo set environment variables on macOS or Linux, run the export command from the terminal: export NYTIMES_KEY='YOUR-API-KEY'"))
    }
  } catch (error) {
    console.error(error.message)
  }
}
```

```
❯ node the-birthday-times.js            
Please set your API key on your operating system.
To set environment variables on macOS or Linux, run the export command from the terminal: export NYTIMES_KEY='YOUR-API-KEY'

:￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣:
:                                                                      :
:              🗞   T h e   B i r t h d a y   T i m e s   🗞             :
:                                                                      :
:                                                                      :
￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣


? 🎂 Your Birthday? › 2022-08-24
```

2022-08-24 23:10 UTC, cafedomancer commented on the-birthday-times.js
> +    throw new Error(color.red("Please set your API key on your operating system.\nTo set environment variables on macOS or Linux, run the export command from the terminal: export NYTIMES_KEY='YOUR-AP
送出された例外はどこかで捕捉する必要があります。`ensureApiKey()` の中で捕捉すると後者のような挙動になってしまうので、`main()` の中で捕捉すると良いんじゃないでしょうか？ 😋

2022-08-24 23:11 UTC, cafedomancer approved these changes
🤩

2022-08-24 23:22 UTC, cafedomancer requested changes
すみません、try catch に関する変更がまだでした...。そちらの変更が終わったら再度 approve させてください。

2022-08-25 03:01 UTC, pachikuriii reviewed
他の箇所にもフィードバックいただきありがとうございます🙏🌸
ご確認いただけますとうれしいです…！

2022-08-25 03:01 UTC, pachikuriii commented on the-birthday-times.js
> +  return _.sampleSize(allNewsIndexNum, 3)
> getnewsIndexNum() は news のランダムな添字を取得する関数という理解で合っていますか？

おっしゃる通りです✨！！

> lodash を使わなくてもよいのですが、lodash の _.sampleSize などから改善案の着想が得られると思うので目を通してみてください

と言っていただいていたのですが、いただいたURLに目を通して30分ほどコードを触ってみていたものの、依然として複雑なコードのままだったため結局lodashを導入する形としました…😅

2022-08-25 03:01 UTC, pachikuriii commented on the-birthday-times.js
> +  }
`main()`にtry...catchを入れて、`ensureApiKey()`内でエラーが投げられた場合ここでエラーを捕捉することとしました…！

2022-08-27 23:58 UTC, cafedomancer commented on the-birthday-times.js
> +  return _.sampleSize(allNewsIndexNum, 3)
添字を要素に持つ配列を作って、そこから必要な数だけランダム似要素を取得する、という考えが理解できていれば OK です 🙆 ✨

2022-08-27 23:58 UTC, cafedomancer approved these changes
🌟

2022-08-28 10:32 UTC, merged